#!/bin/bash
case "$2" in
	squash)
		# do nothing as we don't want to mangle squash commits
		;;
	fixup)
		# dito
		;;
	merge)
		# dito
		;;
	message)
		# dito
		;;
	*)
		# show last commit message:
		echo "# Performing commit as:" >> "$1"
		echo "# $(git config user.name) <$(git config user.email)>" >> "$1"
		echo "#" >> "$1"
		echo "# Parent commit:" >> "$1"
		echo "$(git log -1 | sed -n 's/^\(.*\)$/# \1/p')" >> "$1"
		;;
esac
